name: update-scores
    
on:
  schedule:
    - cron: '30 23 * * 4'
    - cron: '25 9 * * 3'
        # - description: Thursday after TNF
        #   schedule: "30 23 * * 4"
        # - description: Sunday after first block of games
        #   schedule: "0 17 * * 7"
        # - description: Sunday after second block of games
        #   schedule: "30 20 * * 7"
        # - description: Sunday after SNF
        #   schedule: "30 23 * * 7"
        # - description: Monday after MFN
        #   schedule: "30 23 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed.

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: install requirements.txt
        run: pip install -r requirements.txt        

      - name: execute py script # run the run.py to get the latest data
        run: python scripts/update_scores.py
        env:
          MSF_NFL_ID: ${{ secrets.MSF_NFL_ID }}
          MSF_NFL_SECRET: ${{ secrets.MSF_NFL_SECRET }}