name: update-overall-records
    
on:
  schedule:
    - cron: '0 10 * * FRI' # UTC - Friday @ 10 AM UTC, Thursday after TNF
    - cron: '0 10 * * MON' # UTC - Monday @ 10 AM UTC, Sunday after all games
    - cron: '0 10 * * TUE' # UTC - Tuesday @ 10 AM UTC, Monday after all games

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Los_Angeles

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed.

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: install requirements.txt
        run: pip install -r requirements.txt        

      - name: execute py script # run the run.py to get the latest data
        run: python scripts/update_scores.py
        env:
          MSF_NFL_ID: ${{ secrets.MSF_NFL_ID }}
          MSF_NFL_SECRET: ${{ secrets.MSF_NFL_SECRET }}