name: update-scores
    
on:
  schedule:
    - cron: 35 9 * * 2 # testing
    - cron: 30 23 * * 3 # Thursday after TNF
    - cron: 0 17 * * 6 # Sunday after first block of games
    - cron: 30 20 * * 6 # Sunday after second block of games
    - cron: 30 23 * * 6 # Sunday after SNF
    - cron: 30 23 * * 0 # Monday after MFN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed.

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Use gcloud CLI
        run: gcloud info

      - name: install requirements.txt
        run: pip install -r requirements.txt        

      - name: execute py script # run the run.py to get the latest data
        run: python scripts/update_scores.py
        env:
          MSF_NFL_ID: ${{ secrets.MSF_NFL_ID }}
          MSF_NFL_SECRET: ${{ secrets.MSF_NFL_SECRET }}